### ISSUE TITLE
Add Note to "Consume and test a third-party REST API" Guide

### ISSUE THREAD

**Issue by cjstehno** [grails-guides/grails-mock-http-server#1]
I realize that the Consume and test a third-party REST API Guide is using Ersatz v1.4.0 (current is 1.5.0), but I figured it would be good to have a warning in place since it's targeted at Grails users.

In 1.5.0 I have upgraded the version of Undertow used in Ersatz, which may cause problems with Grails testing when using the Undertow embedded server. There is a shadow jar version of Ersatz available for such situations (see Shadow Jar in the User Guide).

I would be willing to update the Guide for version 1.5 and add the note about version collisions, but figured I'd let @sdelamo take a crack at it if he wants to.

> Note: I originally posted this on the main [grails-guides project](https://github.com/grails/grails-guides/issues/13) in error.

**Comment by sdelamo** [comment]
@cjstehno  It would be great if you could create pull request with the Guide update. 

I will review it and merge it. 

Thanks in advanced

**Comment by cjstehno** [comment]
Hmm, I thought this would be a simple asciidoc edit job... looks like there is some sort of framework involved. It may be a while before I can get into this. :-/

**Comment by sdelamo** [comment]
To generate the guide locally clone the repo and execute `./gradlew publishGuide`. 

The asciidoctor documents are under `src/main/docs/guide`

**Comment by cjstehno** [comment]
Created Pull Request: #2
