### ISSUE TITLE
Which http client library should be used instead of "org.grails:grails-datastore-rest-client"?

### ISSUE THREAD

**Issue by jfuentestgn** [grails-guides/grails-mock-http-server#3]
I recently realized that the "grails-datastore-rest-client" module has been removed from the current master branch in the grails-data-mapping project.

As this guide uses it as a client library... which would be the replacement for next versions? Is there any recommended library for new grails 3 projects?

Thanks

**Comment by niravassar** [comment]
The grails 4 version deprecates the `grails-datastore-rest-client`.  The master branches are all coded for grails 4 versions, as we are preparing for a release. 
the micronaut http client is the one of choice from grail 4 onwards. 

Howevrer grails 3.3.9 still uses `grails-datastore-rest-client`

**Comment by jfuentestgn** [comment]
Thanks!! I'll try grails-datastore-rest-client while waiting for grails4 ;)
